// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WfN0Ha9P4vwRXw7AaCIBmXIn1kX2dqs',
    appId: '1:636200481801:web:14ae407730b92ffd2af4d8',
    messagingSenderId: '636200481801',
    projectId: 'ai-fitness-coach-c0d30',
    authDomain: 'ai-fitness-coach-c0d30.firebaseapp.com',
    storageBucket: 'ai-fitness-coach-c0d30.firebasestorage.app',
    measurementId: 'G-G048Y72068',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUlut2Kw3PaVfGiPKwYJ4bvEjqJFRYdqk',
    appId: '1:636200481801:ios:edfea561f12328462af4d8',
    messagingSenderId: '636200481801',
    projectId: 'ai-fitness-coach-c0d30',
    storageBucket: 'ai-fitness-coach-c0d30.firebasestorage.app',
    iosBundleId: 'com.example.aiFitnessCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_WfN0Ha9P4vwRXw7AaCIBmXIn1kX2dqs',
    appId: '1:636200481801:web:6e533178497aea652af4d8',
    messagingSenderId: '636200481801',
    projectId: 'ai-fitness-coach-c0d30',
    authDomain: 'ai-fitness-coach-c0d30.firebaseapp.com',
    storageBucket: 'ai-fitness-coach-c0d30.firebasestorage.app',
    measurementId: 'G-PER8E90QTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw2HhH98oJZZyI8joXT1QvEuFcT3h0F0M',
    appId: '1:636200481801:android:10150820864b9be12af4d8',
    messagingSenderId: '636200481801',
    projectId: 'ai-fitness-coach-c0d30',
    storageBucket: 'ai-fitness-coach-c0d30.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUlut2Kw3PaVfGiPKwYJ4bvEjqJFRYdqk',
    appId: '1:636200481801:ios:3136097cb9013aca2af4d8',
    messagingSenderId: '636200481801',
    projectId: 'ai-fitness-coach-c0d30',
    storageBucket: 'ai-fitness-coach-c0d30.firebasestorage.app',
    iosClientId: '636200481801-0mu6copm6ijmfkp0ketvpbaq64j7eocb.apps.googleusercontent.com',
    iosBundleId: 'com.liftsforge.app',
  );
}
